// Generated by scripts/generate-icons.py.
enum SideEyeBlink {
    static let frameCount = 6
    static let openness: [Double] = [1, 0.82, 0.55, 0.28, 0.1, 0]
    static let steps: [(frame: Int, milliseconds: Int)] = [(1, 16), (2, 18), (3, 20), (4, 22), (5, 50), (4, 28), (3, 30), (2, 32), (1, 36), (0, 30)]
    static let interval = 8.0...14.0
}
