#!/usr/bin/env python3
"""Export Side Eye 03 and its blink frames. Requires macOS sips and librsvg."""

import json
from pathlib import Path
import re
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "design"
ASSETS = ROOT / "App/Assets.xcassets"
# Close quickly, hold briefly, then reopen more gently (282 ms total).
STEPS = [(1, 16), (2, 18), (3, 20), (4, 22), (5, 50),
         (4, 28), (3, 30), (2, 32), (1, 36), (0, 30)]
OPENNESS = [1, 0.82, 0.55, 0.28, 0.10, 0]


def run(*args):
    subprocess.run(args, check=True, stdout=subprocess.DEVNULL)


def main():
    if not shutil.which("rsvg-convert"):
        raise SystemExit("Install librsvg (brew install librsvg), then rerun this script.")
    source = (DESIGN / "menu-bar-icon.svg").read_text()
    frames_dir = DESIGN / "blink"
    frames_dir.mkdir(exist_ok=True)
    for frame, openness in enumerate(OPENNESS):
        svg = source
        if frame == 5:
            # A fine curved slit reads as a closed lid, even at menu bar size.
            svg = re.sub(r'<path id="eye"[^>]*/>',
                         '<path id="eye" d="M3.6 10.5Q9 11 14.4 10.3" '
                         'fill="none" stroke="black" stroke-width=".65" stroke-linecap="round"/>', svg)
            svg = re.sub(r'\s*<ellipse[^>]*/>', '', svg)
        elif frame:
            # Only the opening narrows. The pupil, tile, and leaves never scale.
            svg = svg.replace('<path id="eye" ',
                              f'<path id="eye" transform="translate(0 10.5) scale(1 {openness}) translate(0 -10.5)" ')
        svg_path = frames_dir / f"frame-{frame}.svg"
        svg_path.write_text(svg)
        name = "SideEye" if frame == 0 else f"SideEyeBlink{frame}"
        asset_dir = ASSETS / f"{name}.imageset"
        asset_dir.mkdir(exist_ok=True)
        images = []
        for scale in (1, 2):
            filename = f"{name}@{scale}x.png"
            run("rsvg-convert", "-w", str(18 * scale), "-h", str(18 * scale),
                "-o", str(asset_dir / filename), str(svg_path))
            images.append({"filename": filename, "idiom": "mac", "scale": f"{scale}x"})
        (asset_dir / "Contents.json").write_text(json.dumps({
            "images": images, "info": {"author": "xcode", "version": 1},
            "properties": {"template-rendering-intent": "template"},
        }, indent=2) + "\n")

    app_icon = ASSETS / "AppIcon.appiconset"
    for image in json.loads((app_icon / "Contents.json").read_text())["images"]:
        size = int(image["size"].split("x")[0]) * int(image["scale"][0])
        run("sips", "-z", str(size), str(size), str(DESIGN / "app-icon.png"),
            "--out", str(app_icon / image["filename"]))

    swift_steps = ", ".join(f"({frame}, {ms})" for frame, ms in STEPS)
    (ROOT / "App/SideEyeBlink.swift").write_text(
        '// Generated by scripts/generate-icons.py.\n'
        'enum SideEyeBlink {\n'
        f'    static let frameCount = {len(OPENNESS)}\n'
        f'    static let openness: [Double] = {OPENNESS}\n'
        f'    static let steps: [(frame: Int, milliseconds: Int)] = [{swift_steps}]\n'
        '    static let interval = 8.0...14.0\n'
        '}\n'
    )
    preview = '''<!doctype html>
<html lang="en"><meta charset="utf-8"><title>Side Eye — blink preview</title>
<style>
body{font:15px -apple-system,sans-serif;background:#f5f1e9;color:#252820;margin:48px auto;max-width:850px;padding:0 24px}h1{font-size:40px;letter-spacing:-1.5px}p{color:#64685e;line-height:1.6}.row{display:flex;gap:18px;margin:24px 0}.sample{display:flex;align-items:center;justify-content:center;gap:8px;flex:1;min-height:110px;border-radius:18px;background:#e2e0da}.dark{background:#303431;color:white}.dark img{filter:invert(1)}.large{width:72px;height:72px}.actual{width:18px;height:18px}.frames{display:flex;gap:30px;margin:25px 0}.frames img{width:54px;height:54px}button{font:inherit;padding:10px 18px;cursor:pointer}label{margin-left:18px}a{color:inherit}
</style>
<h1>Side Eye. A proper little blink.</h1>
<p>The leaves and square stay still. The eyelids close over a fixed pupil, pause, then reopen a little more slowly. The app blinks every 8–14 seconds; this preview can repeat faster.</p>
<div class="row"><div class="sample"><img class="actual live" src="blink/frame-0.svg" alt="Side Eye">24:59</div><div class="sample dark"><img class="actual live" src="blink/frame-0.svg" alt="Side Eye">24:59</div></div>
<div class="row"><div class="sample"><img class="large live" src="blink/frame-0.svg" alt="Enlarged Side Eye"></div><div class="sample dark"><img class="large live" src="blink/frame-0.svg" alt="Enlarged Side Eye"></div></div>
<button id="blink">Blink once</button><label><input type="checkbox" id="repeat"> Repeat every 2 seconds</label>
<p>All six frames, open → closed:</p><div class="frames">FRAMES</div>
<script>
const steps=STEPS, live=[...document.querySelectorAll('.live')], reduced=matchMedia('(prefers-reduced-motion: reduce)');
let timer, blinking=false, generation=0;
for(let i=0;i<6;i++){const image=new Image();image.src=`blink/frame-${i}.svg`;}
function setFrame(frame){live.forEach(image=>image.src=`blink/frame-${frame}.svg`);}
async function blink(){if(blinking||reduced.matches)return;blinking=true;const current=++generation;for(const [frame,ms] of steps){if(current!==generation)return;setFrame(frame);await new Promise(resolve=>setTimeout(resolve,ms));}blinking=false;}
function stop(){clearInterval(timer);generation++;blinking=false;setFrame(0);}
document.querySelector('#blink').onclick=blink;
document.querySelector('#repeat').onchange=event=>{stop();if(event.target.checked&&!reduced.matches){blink();timer=setInterval(blink,2000);}};
reduced.addEventListener('change',()=>{stop();document.querySelector('#repeat').checked=false;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();document.querySelector('#repeat').checked=false;}});
</script></html>
'''.replace('FRAMES', ''.join(f'<img src="blink/frame-{i}.svg" alt="Frame {i}">' for i in range(6)))
    (DESIGN / "blink-preview.html").write_text(preview.replace('STEPS', json.dumps(STEPS)))
    print("Exported version 03 app icon, six template frames, and blink-preview.html")


if __name__ == "__main__":
    main()
